### ISSUE TITLE
Provide ability to validate base language w/ out comparison

### ISSUE THREAD

**Issue by namolnad** [Asana/locheck#13]
It would be nice if the tool could validate the base language without comparing it to translations to see if there are issues with things like position identifiers within stringsdict files. This would be great as an initial check that things are being properly formatted before being sent to translators, for instance.

**Comment by stevelandeyasana** [comment]
Would the `--ignore-missing` option in #11 solve this problem for you? It discards warnings related to strings appearing in one localization but not another.

An easy fix would be to just stop throwing errors if no translations are passed, and just run the internal validation on the base language.

**Comment by namolnad** [comment]
I do think that would likely work for my team's needs — it might not be quite as clear from a user perspective as the second option you've presented, but I think it would work. Either way, thanks for considering and for your work on this!

**Comment by stevelandeyasana** [comment]
Will be fixed by #17.

**Comment by namolnad** [comment]
Thanks for the fix/addition!
