### ISSUE TITLE
Duplicate keys or values in base language file strings.xml or localization .strings are not reported will be good to have 

### ISSUE THREAD

**Issue by AnilVarturi11** [Asana/locheck#30]

**Comment by stevelandeyasana** [comment]
Can you give an example of some strings that would have this problem?

**Comment by alex-hunsley-nl** [comment]
Just here to say +1 for this.

I'm just fixing a badly maintained localization file set and there are keys and values that are just outright duplicated:

`
"thing.key" = "hello there"
"thing.key" = "hello there"
`

But at the same time, you'd probably also like to detect:

`
"thing.key" = "hello there"
"thing.key" = "goodbye there"
`

i.e. a duplicated key regardless of values being different

**Comment by stevelandeyasana** [comment]
Thanks for the example! I opened a PR with an implementation. It'll be in the next release.
