### ISSUE TITLE
discoverlproj fails with space in dir name

### ISSUE THREAD

**Issue by philmitchell** [Asana/locheck#46]
The `xcstrings` command works, but `discoverlproj` fails with a "File does not exist" error.

This is on MacOS.

Thanks for the invaluable tool!

**Comment by stevelandeyasana** [comment]
Can you please paste the full command you're running, and what the lproj paths are in your source tree?

**Comment by philmitchell** [comment]
`locheck discoverlproj "/Users/phil/dev/client_repo/source\ dir"`

/Users/phil/dev/client_repo/source\ dir/Base.lproj/
/Users/phil/dev/client_repo/source\ dir/English.lproj/
/Users/phil/dev/client_repo/source\ dir/en-AU.lproj/
/Users/phil/dev/client_repo/source\ dir/en-GB.lproj/
/Users/phil/dev/client_repo/source\ dir/en-NZ.lproj/
/Users/phil/dev/client_repo/source\ dir/en.lproj/

**Comment by stevelandeyasana** [comment]
Yeah, that does look correct. I'll look into this some time in the next couple weeks, though if you're feeling adventurous, you could check out the code and add some breakpoints here: https://github.com/Asana/locheck/blob/main/Sources/LocheckCommand/main.swift#L319

**Comment by stevelandeyasana** [comment]
Oh, I just realized - your shell commant includes a `\` in the quoted string, which isn't necessary. You either need quotes, or the backslash. Could you please try removing either one?

**Comment by philmitchell** [comment]
Steve, you are right ... it works fine. Sorry for the noise and thanks for the quick response!

**Comment by stevelandeyasana** [comment]
No problem!
